dist: xenial
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
 
install:
  - apt search libsfml
  - apt search libsfml-dev
  - sudo apt install libsfml-dev

os: lunux
addons:
  apt:
    sources:
      - ubuntu-toolchan-r-test
    packages:
     - g++-6
     - gcc-6
     - cmake

script:
  - export CC=gcc-6
  - export CXX=g++-6
  - cmake --version
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
