language: cpp
compiler: gcc

os: lunux
addons:
  apt:
    sources:
      - ubuntu-toolchan-r-test
    packages:
     - g++-7
     - gcc-7
     - cmake

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake CMakeLists.txt
  - cmake --build .
