dist: xenial
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install libpthread-*
  
os: linux
addons:
  apt:
    packages:
     - g++-6
     - gcc-6
     - cmake
     - libsfml-dev

script:
  - export CC=gcc
  - export CXX=g++
  - cmake --version
  - gcc --version
  - g++ --version
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
