dist: trusty
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install libpthread-*
  
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
      - key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key' 
    packages:
      - cmake
      - libsfml-dev
      - clang-6.0
      - libstdc++6
      - libpng-dev
      - build-essential

script:
  - export CC=clang-6.0
  - export CXX=clang++-6.0
  - export MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
  - export LINKER_FLAGS="-stdlib=libc++ -lc++abi"
  - cmake --version
  - mkdir build
  - cd build
  - cmake ../ 
  - cmake --build .
