dist: xenial
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
 
install:
  - apt search libsfml
  - apt search libsfml-dev
  - sudo apt install -y libsfml-dev
  - sudo apt-get install -y libpthread-stubs0-dev
  - sudo apt-get install -y libgl1-mesa-dev
  - sudo apt-get install -y libx11-dev
  - sudo apt-get install -y libxrandr-dev
  - sudo apt-get install -y libfreetype6-dev
  - sudo apt-get install -y libglew1.5-dev
  - sudo apt-get install -y libjpeg8-dev
  - sudo apt-get install -y libsndfile1-dev
  - sudo apt-get install -y libopenal-dev
  - sudo apt-get install -y libudev-dev
  - sudo apt-get install -y libxcb-image0-dev
  - sudo apt-get install libflac-dev
  - sudo apt-get install libjpeg-dev
  
os: lunux
addons:
  apt:
    sources:
      - ubuntu-toolchan-r-test
    packages:
     - g++-6
     - gcc-6
     - cmake

script:
  - export CC=gcc
  - export CXX=g++
  - cmake --version
  - gcc --version
  - g++ -version
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
