dist: xenial
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
 
install:
  - apt search libsfml
  - sudo apt install -y libsfml-dev
  - sudo apt-get install libfreetype6-dev libx11-dev libxrandr-dev libgl1-mesa-dev libudev-dev libopenal-dev libflac-dev libogg-dev libvorbis-dev -y
  
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchan-r-test
    packages:
     - g++-6
     - gcc-6
     - cmake
     - libsfml-dev

script:
  - export CC=gcc
  - export CXX=g++
  - cmake --version
  - gcc --version
  - g++ --version
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
