version: '{build}'
branches:
  only:
    - TMXL_V1

clone_folder: c:\projects\cmake-init

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Release
  - Debug
platform:
  - x64

environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- echo %generator%

before_build:
- cmd: |-
    cd TMXL
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
#    dir
#    tree c:\projects\cmake-init /F

build:
  project: c:\projects\cmake-init\TMXL\build\Project.sln
  verbosity: minimal
  parallel: true
